import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ru' | 'fr';

interface LanguageContextType {
  language: Language;
  currentLanguage: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Переводы
const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.experience': 'Experience',
    'nav.skills': 'Skills',
    'nav.cases': 'Case Studies',
    'nav.portfolio': 'Portfolio',
    'nav.education': 'Education',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.title': 'Olga Morozova',
    'hero.subtitle': 'Editor-in-Chief, Content Strategist, and Project Manager',
    'hero.description': 'I help companies create strong content that drives audience and business growth.',
    'hero.phone': '+7 (916) 841-32-16',
    'hero.email': 'morozova31@gmail.com',
    'hero.telegram': '@oljona',
    'hero.location': 'Moscow / Remote',
    'hero.portfolioButton': 'View Portfolio',
    'hero.githubButton': 'GitHub',
    
    // About Section
    'about.title': 'Who am I',
    'about.description': 'Digital knowledge manager with 10+ years of experience in digital libraries, content strategy, and educational projects.',
    'about.experience': 'I organize information systems, create user-friendly interfaces, and develop content strategies to make knowledge accessible to everyone.',
    'about.systematic': 'Systematic approach',
    'about.systematicDesc': 'I build processes, automate routine, and create order in information chaos.',
    'about.result': 'Result-oriented',
    'about.resultDesc': 'I focus on measurable results and business value.',
    'about.team': 'Teamwork',
    'about.teamDesc': 'I know how to build and motivate teams for complex projects.',
    'about.projects': 'Successful projects',
    'about.projectsDesc': 'I have launched and managed dozens of digital products and services.',
    'about.p1': 'I help organizations and people find, structure, and use knowledge.',
    'about.p2': 'My experience includes digital libraries, educational platforms, and content strategies.',
    'about.p3': 'I am passionate about making knowledge accessible and useful for everyone.',
    'about.highlights': 'Key Qualities:',
    'about.desiredTitle': 'Desired Position',
    'about.desiredPosition': 'Digital Knowledge Manager / Content Strategist',
    'about.employment': 'Full-time, remote or hybrid, project work.',
    
    // Skills Section
    'skills.title': 'Key Competencies',
    'skills.subtitle': 'Professional skills and expertise in various fields',
    'skills.professional': 'Professional Skills',
    'skills.technical': 'Technical Skills',
    'skills.languages': 'Language Skills',
    'skills.projectManagement': 'Project Management',
    'skills.contentStrategy': 'Content Strategy',
    'skills.productThinking': 'Product Thinking',
    'skills.dataAnalytics': 'Data Analytics',
    'skills.systemThinking': 'System Thinking',
    'skills.teamManagement': 'Team Management',
    'skills.analytics': 'Analytics',
    'skills.projectManagementCat': 'Project Management',
    'skills.contentCreation': 'Content Creation',
    'skills.automation': 'Automation',
    'skills.processes': 'Processes',
    'skills.systems': 'Systems',
    'skills.documentation': 'Documentation',
    'skills.russian': 'Russian',
    'skills.english': 'English',
    'skills.french': 'French',
    'skills.native': 'Native',
    'skills.digitalLibraries': 'Digital Libraries',
    'skills.userExperience': 'User Experience',
    'skills.informationArchitecture': 'Information Architecture',
    'skills.digitalTransformation': 'Digital Transformation',
    
    // Experience Section
    'experience.title': 'Work Experience',
    'experience.company': 'Russian State Library',
    'experience.position': 'Editor-in-Chief of the "Svet" mobile app',
    'experience.location': 'Moscow',
    'experience.period': 'February 2022 — January 2025',
    'experience.description': 'Led the product team responsible for content, analytics, and development of a digital service for millions of users.',
    'experience.achievements': 'Key achievements:',
    'experience.ach1': 'Increased KPI (book loans) 3x (up to 2.5–3 million per year) through content strategy, partnerships, and analytics',
    'experience.ach2': 'Developed and coordinated 17 major partnership projects',
    'experience.ach3': 'Cooperation with Moscow Electronic School — 3 million potential users, 100,000 book loans in 2024',
    'experience.ach4': '"Summer with Pyaterochka" campaign — coverage of 1,350 stores, 10x increase in website visits in a month',
    'experience.ach5': 'Built a data collection and visualization system (Yandex.Metrica, Superset, Excel)',
    'experience.ach6': 'Created internal automation services — reduced text preparation time from 2 days to 30 minutes',
    'experience.ach7': 'Moved the team to a Russian tool (Kaiten), creating a process control system',
    'experience.ach8': 'Developed 11 landing pages in Tilda',
    'experience.ach9': 'Managed an editorial team of 5 people',
    'experience.current': 'Current',
    
    // Education Section
    'education.title': 'Education and Professional Development',
    'education.education': 'Education',
    'education.certifications': 'Certifications',
    'education.degree1': 'Master of Journalism',
    'education.institution1': 'Lomonosov Moscow State University',
    'education.program1': 'International program: Mastère franco-russe de journalisme',
    'education.degree2': 'Philology',
    'education.institution2': 'Novosibirsk State University',
    'education.cert1': 'Certified Agile Professional',
    'education.cert2': 'Product Analytics',
    'education.cert3': 'Agile Development (Agile) with Jira',
    'education.cert4': 'Copyright Law',
    'education.certOrg4': 'VOIS',
    'education.cert5': 'Data Analysis Tools',
    'education.certOrg5': 'Yandex Practicum',
    'education.cert6': 'Project Manager',
    'education.certOrg6': 'Yandex Practicum',
    'education.cert7': 'Content Marketing',
    'education.certOrg7': 'Netology',
    
    // Portfolio Section
    'portfolio.title': 'Portfolio',
    'portfolio.subtitle': 'Examples of my projects: landing pages, promo sites, instructions, and design systems',
    'portfolio.landingProjects': 'Special Project Landing Pages',
    'portfolio.texts': 'Texts & Photos',
    'portfolio.loveBooks': 'Books about Happy Love',
    'portfolio.loveBooksDesc': 'Thematic landing page for promoting a collection of love books',
    'portfolio.readingInSky': 'Reading in the Sky',
    'portfolio.readingInSkyDesc': 'Promo site for a joint reading project',
    'portfolio.gamzatov100': '100 Years of Rasul Gamzatov',
    'portfolio.gamzatov100Desc': 'Anniversary project for the poet\'s centenary',
    'portfolio.newYear2025': 'New Year Predictions',
    'portfolio.newYear2025Desc': 'Interactive New Year project',
    'portfolio.pushkin225': 'Quiz for the 225th Anniversary of A.S. Pushkin',
    'portfolio.pushkin225Desc': 'Online quiz for the great poet\'s anniversary',
    'portfolio.posters': 'Posters and Handouts',
    'portfolio.pushkinColoring': 'Coloring Pages for A.S. Pushkin\'s Anniversary',
    'portfolio.pushkinColoringDesc': 'Children\'s coloring pages for popularizing Pushkin\'s work',
    'portfolio.newYearDecorations': 'New Year Decorations with Project Symbolism',
    'portfolio.newYearDecorationsDesc': 'Branded New Year materials',
    'portfolio.libraryInfographics': 'Library Infographics',
    'portfolio.libraryInfographicsDesc': 'Information materials for partner libraries',
    'portfolio.manuals': 'Instructions and Manuals',
    'portfolio.mobileLibraries2024': 'Mobile Libraries Manual 2024',
    'portfolio.mobileLibraries2024Desc': 'Detailed instructions for working with mobile libraries',
    'portfolio.brandedIllustrations': 'Branded Illustration Templates',
    'portfolio.brandedIllustrationsDesc': 'Figma templates for creating project posters in a unified style',
    'portfolio.digitalMerch': 'Digital Merchandise',
    'portfolio.telegramStickers': 'Telegram Stickers',
    'portfolio.telegramStickersDesc': 'Set of branded stickers for Telegram messenger',
    'portfolio.additionalMaterials': 'Additional Materials',
    'portfolio.githubProfile': 'GitHub Profile',
    'portfolio.texts1': 'Days of Tajikistan Culture at the Russian State Library',
    'portfolio.texts1Desc': 'Report from the opening of two exhibitions dedicated to the Days of Culture of the Republic of Tajikistan in Russia.',
    'portfolio.texts1Url': 'https://www.rsl.ru/ru/events/afisha/vistavki/dni-kultury-tadzhikistana-v-rgb',
    'portfolio.texts2': '18th International Scientific Readings in Memory of Nikolai Fedorov',
    'portfolio.texts2Desc': 'Solemn opening of the 18th International Scientific Readings in memory of philosopher N. F. Fedorov.',
    'portfolio.texts2Url': 'https://www.rsl.ru/ru/all-news/xviii-fedorovskie-chtenia',
    'portfolio.texts3': 'Round Table "Unique Linguistic Heritage of Indigenous Peoples of the North"',
    'portfolio.texts3Desc': 'Round table dedicated to the International Year of Indigenous Languages of the North.',
    'portfolio.texts3Url': 'https://www.rsl.ru/ru/events/afisha/meetings/kruglyij-stol-unikalnyij-lingvisticheskij-fond',
    'portfolio.texts4': 'Round Table "UN Day at the Russian State Library — 2019"',
    'portfolio.texts4Desc': 'Round table dedicated to UN Day and the 74th session of the UN General Assembly.',
    'portfolio.texts4Url': 'https://www.rsl.ru/ru/events/afisha/meetings/kruglyij-stol-den-oon-v-rgb-2019',
    'portfolio.texts5': 'Photo Exhibition of Southern Crimea Landscapes at the Russian State Library',
    'portfolio.texts5Desc': 'Opening of the banner exhibition "Dream Coast. Cultural and Natural Heritage of the Southern Coast of Crimea."',
    'portfolio.texts5Url': 'https://www.rsl.ru/ru/all-news/fotovyistavka-pejzazhej-yuzhnogo-berega-kryima',
    'portfolio.texts6': 'Taking Photos',
    'portfolio.texts6Desc': 'The "anonymous" stage of the competition for the best photo reportage about Moscow "Silver Camera-2005" has started.',
    'portfolio.texts6Url': 'https://web.archive.org/web/20061130092311/http://lenta.ru:80/articles/2006/10/03/foto/',
    'portfolio.texts7': 'Both Houellebecqian and Sickening',
    'portfolio.texts7Desc': 'The scandalous French writer brought a new novel to Russia',
    'portfolio.texts7Url': 'https://web.archive.org/web/20120214221335/http://lenta.ru:80/articles/2006/04/20/houellebecq/',
    'portfolio.texts8': '"I Hope You Didn\'t Buy My Book"',
    'portfolio.texts8Desc': 'Frederic Beigbeder flew in for a date with Moscow',
    'portfolio.texts8Url': 'https://web.archive.org/web/20120708064328/http://lenta.ru/articles/2006/07/03/beigbeder/',
    'portfolio.texts9': 'A Date with Cthulhu',
    'portfolio.texts9Desc': 'A novel about sea monsters captured bookstore windows',
    'portfolio.texts9Url': 'https://disk.yandex.ru/i/5dekldkfLa54dA',
    'portfolio.texts10': 'Yulia Napolova: "Letters Remain in the Museum"',
    'portfolio.texts10Desc': 'Interview with the designer of the exhibition "Time to Gather... Prince Yusupov and His Library"',
    'portfolio.texts10Url': 'https://www.rsl.ru/ru/all-news/julia-napolova-interview',
    
    // Graphic Design Portfolio
    'portfolio.graphicDesign': 'Graphic Design',
    'portfolio.socialIllustrations': 'Social Media Illustrations',
    'portfolio.socialIllustrationsDesc': 'Collection of illustrations for social media posts and promotional materials',
    'portfolio.bookCovers': 'Book Covers',
    'portfolio.bookCoversDesc': 'Creative book cover designs with modern typography and visual elements',
    'portfolio.postersAndDiplomas': 'Posters and Diplomas',
    'portfolio.postersAndDiplomasDesc': 'Event posters, certificates, and diploma designs for various organizations',
    'portfolio.designProjects': 'Design Projects',
    'portfolio.printMaterials': 'Print Materials',
    'portfolio.digitalDesign': 'Digital Design',
    
    // Contact Section
    'contact.title': 'Contact Me',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.telegram': 'Telegram',
    'contact.linkedin': 'LinkedIn',
    'contact.footer': '2025 • Olga Morozova • Created in Make',
    
    // Case Studies Section
    'cases.title': 'Case Studies',
    'cases.subtitle': 'Real projects with measurable results and business impact',
    
    // Aeroflot Case
    'cases.aeroflot.title': 'Aeroflot In-flight Audiobooks',
    'cases.aeroflot.backgroundTitle': 'Background',
    'cases.aeroflot.background': 'Aeroflot, Russia\'s flagship airline, wanted to enhance its in-flight passenger experience with engaging digital content. As part of the partnership between Aeroflot and the Russian State Library, we developed a multimedia audiobook service accessible on board.',
    'cases.aeroflot.roleTitle': 'My Role',
    'cases.aeroflot.role1': 'Led content curation: selected and organized a collection of audiobooks tailored for in-flight audiences',
    'cases.aeroflot.role2': 'Developed content design standards: created audiobook covers using AI-generated artwork',
    'cases.aeroflot.role3': 'Oversaw content integration: coordinated publication standards for both Aeroflot\'s application and the project\'s landing page',
    'cases.aeroflot.role4': 'Collaborated with technical teams to ensure smooth delivery and accessibility',
    'cases.aeroflot.processTitle': 'Process',
    'cases.aeroflot.process1': 'Researched passenger content preferences and identified a diverse selection of audiobooks',
    'cases.aeroflot.process2': 'Designed a content production workflow that included cover design, metadata preparation, and content formatting',
    'cases.aeroflot.process3': 'Created a dedicated landing page for promotion and ease of navigation',
    'cases.aeroflot.process4': 'Applied AI tools to generate cohesive and appealing cover designs, ensuring a modern, innovative aesthetic',
    'cases.aeroflot.resultsTitle': 'Results',
    'cases.aeroflot.result1': 'Successfully launched a new digital entertainment feature for Aeroflot passengers',
    'cases.aeroflot.result2': 'Project was presented to the Minister of Culture and Deputy Minister of Education and received official approval and positive recognition',
    'cases.aeroflot.result3': 'Strengthened Aeroflot\'s positioning as an innovator in passenger experience',
    'cases.aeroflot.result4': 'Demonstrated the potential of integrating AI-driven design into large-scale cultural and commercial projects',
    'cases.aeroflot.highlightsTitle': 'Key Highlights',
    'cases.aeroflot.highlight1': 'Enterprise partnership with a national airline',
    'cases.aeroflot.highlight2': 'AI-powered design innovation',
    'cases.aeroflot.highlight3': 'High-level recognition by government officials',
    'cases.aeroflot.highlight4': 'Cross-functional project management (content, design, technical integration)',
    
    // MESH Case
    'cases.mesh.title': 'Moscow Electronic School Integration',
    'cases.mesh.backgroundTitle': 'Background',
    'cases.mesh.background': 'The Moscow Electronic School (MESH) is one of the largest educational digital platforms in Russia, providing millions of students and teachers with access to learning resources. The Russian State Library sought to integrate its digital catalog into MESH to ensure free access to essential literary works for school curricula.',
    'cases.mesh.roleTitle': 'My Role',
    'cases.mesh.role1': 'Coordinated the integration of our digital library with MESH via API',
    'cases.mesh.role2': 'Selected and curated a catalog of books aligned with school programs',
    'cases.mesh.role3': 'Supervised content preparation, including metadata, annotations, and formatting',
    'cases.mesh.role4': 'Acted as a liaison between developers, editors, and education stakeholders',
    'cases.mesh.processTitle': 'Process',
    'cases.mesh.process1': 'Defined technical requirements and coordinated API implementation with the development team',
    'cases.mesh.process2': 'Managed the editorial process to ensure accuracy and compliance with educational standards',
    'cases.mesh.process3': 'Oversaw quality assurance of content delivery and user accessibility',
    'cases.mesh.process4': 'Engaged with education partners to align content with teaching needs',
    'cases.mesh.resultsTitle': 'Results',
    'cases.mesh.result1': 'Successfully integrated thousands of books into the MESH ecosystem',
    'cases.mesh.result2': 'Provided free access to literature for over 1 million students and teachers',
    'cases.mesh.result3': 'Enhanced the educational value of the platform by aligning content with official curricula',
    'cases.mesh.result4': 'Strengthened the library\'s role as a national leader in digital education initiatives',
    'cases.mesh.highlightsTitle': 'Key Highlights',
    'cases.mesh.highlight1': 'Large-scale B2B educational partnership',
    'cases.mesh.highlight2': 'API-driven integration with a major digital platform',
    'cases.mesh.highlight3': 'Direct social impact: 1M+ students and teachers reached',
    'cases.mesh.highlight4': 'Expertise in coordinating technical and editorial teams',
    
    // Metro Case
    'cases.metro.title': 'Moscow Metro "Underground Reading Hall"',
    'cases.metro.backgroundTitle': 'Background',
    'cases.metro.background': 'The Moscow Metro, one of the busiest public transport systems in the world, wanted to engage passengers with cultural initiatives. Together with the Russian State Library, we transformed one of the metro stations into an interactive "Underground Reading Hall," allowing passengers to access curated books via QR codes.',
    'cases.metro.roleTitle': 'My Role',
    'cases.metro.role1': 'Developed the content concept and curated the digital library for the project',
    'cases.metro.role2': 'Designed mechanics of QR-code access, ensuring smooth user experience',
    'cases.metro.role3': 'Coordinated with metro authorities and technical teams for implementation',
    'cases.metro.role4': 'Oversaw communication materials and user guidance',
    'cases.metro.processTitle': 'Process',
    'cases.metro.process1': 'Selected a diverse collection of books tailored for short and long commutes',
    'cases.metro.process2': 'Created a system of QR codes placed throughout the station, linking directly to library resources',
    'cases.metro.process3': 'Ensured technical functionality and accessibility of the links across devices',
    'cases.metro.process4': 'Monitored user interactions and media mentions to measure engagement',
    'cases.metro.resultsTitle': 'Results',
    'cases.metro.result1': 'Launched the first interactive cultural initiative in the Moscow Metro',
    'cases.metro.result2': 'Turned a public transport hub into a branded cultural experience',
    'cases.metro.result3': 'Generated widespread media attention and positive feedback from passengers',
    'cases.metro.result4': 'Strengthened the library\'s image as an innovator in digital engagement',
    'cases.metro.highlightsTitle': 'Highlights',
    'cases.metro.highlight1': 'Creative use of QR technology for cultural engagement',
    'cases.metro.highlight2': 'High-traffic urban environment (thousands of daily passengers)',
    'cases.metro.highlight3': 'Positive user experience and media coverage',
    'cases.metro.highlight4': 'Successful collaboration with public authorities',
    
    // Pushkin Case
    'cases.pushkin.title': 'Alexander Pushkin Anniversary Project',
    'cases.pushkin.backgroundTitle': 'Background',
    'cases.pushkin.background': 'To celebrate the anniversary of Alexander Pushkin, the Russian State Library initiated a large-scale hybrid project to engage both online and offline audiences. The initiative aimed to promote classical literature in a modern, interactive format.',
    'cases.pushkin.roleTitle': 'My Role',
    'cases.pushkin.role1': 'Designed the overall content concept and quiz structure',
    'cases.pushkin.role2': 'Produced multi-format content: quizzes, printable materials, stickers, and coloring books',
    'cases.pushkin.role3': 'Coordinated nationwide participation, working with 140 libraries across 50 regions',
    'cases.pushkin.role4': 'Directed both online and offline distribution of content and activities',
    'cases.pushkin.processTitle': 'Process',
    'cases.pushkin.process1': 'Developed engaging quiz questions tailored to diverse audiences',
    'cases.pushkin.process2': 'Prepared design assets for both digital and physical participation',
    'cases.pushkin.process3': 'Created guidelines and communication kits for regional libraries',
    'cases.pushkin.process4': 'Managed feedback loop to ensure smooth rollout across all regions',
    'cases.pushkin.resultsTitle': 'Results',
    'cases.pushkin.result1': 'Successful nationwide hybrid event involving 140 libraries in 50 regions',
    'cases.pushkin.result2': 'Thousands of participants engaged through online and offline channels',
    'cases.pushkin.result3': 'Enhanced visibility of classical literature among younger audiences',
    'cases.pushkin.result4': 'Recognition from professional community through conference presentations',
    'cases.pushkin.highlightsTitle': 'Highlights',
    'cases.pushkin.highlight1': 'Content operations at scale (multi-format assets, multi-channel distribution)',
    'cases.pushkin.highlight2': 'Large-scale coordination across dozens of regional partners',
    'cases.pushkin.highlight3': 'Demonstrated ability to manage hybrid projects (online + offline)',
    'cases.pushkin.highlight4': 'Promoted cultural heritage through innovative engagement methods',
    
    // PDF Export
    'pdf.button': 'Download Resume DOCX',
    'pdf.description': 'Complete resume in DOCX format',
    'pdf.generating': 'Generating...',
    'pdf.error': 'An error occurred while creating the DOCX. Please try again.',
    
    // Case Studies buttons
    'cases.showDetails': 'Show Details',
    'cases.hideDetails': 'Hide Details',
  } as const,
  
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.about': 'О себе',
    'nav.experience': 'Опыт',
    'nav.skills': 'Навыки',
    'nav.cases': 'Кейсы',
    'nav.portfolio': 'Портфолио',
    'nav.education': 'Образование',
    'nav.contact': 'Контакты',
    
    // Hero Section
    'hero.title': 'Ольга Морозова',
    'hero.subtitle': 'Главный редактор, контент-стратег и руководитель проектов',
    'hero.description': 'Помогаю компаниям создавать сильный контент, который работает на рост аудитории и бизнеса.',
    'hero.phone': '+7 (916) 841-32-16',
    'hero.email': 'morozova31@gmail.com',
    'hero.telegram': '@oljona',
    'hero.location': 'Москва / Удалённо',
    'hero.portfolioButton': 'Посмотреть портфолио',
    'hero.githubButton': 'GitHub',
    
    // About Section
    'about.title': 'О себе',
    'about.description': 'Я руководитель цифровых знаний с более чем 10-летним опытом создания и управления цифровыми библиотеками, контент-стратегиями и образовательными проектами.',
    'about.experience': 'Специализируюсь на организации информационных систем, создании удобных интерфейсов и разработке контент-стратегий, которые делают знания доступными для всех.',
    'about.systematic': 'Системный подход',
    'about.systematicDesc': 'Строю процессы, автоматизирую рутину, навожу порядок в информационном хаосе.',
    'about.result': 'Ориентация на результат',
    'about.resultDesc': 'Работаю на измеримый результат и пользу для бизнеса.',
    'about.team': 'Командная работа',
    'about.teamDesc': 'Умею строить и мотивировать команды для сложных проектов.',
    'about.projects': 'Успешные проекты',
    'about.projectsDesc': 'Запустила и вела десятки цифровых продуктов и сервисов.',
    'about.p1': 'Помогаю организациям и людям находить, структурировать и использовать знания.',
    'about.p2': 'В моём опыте — цифровые библиотеки, образовательные платформы, контент-стратегии.',
    'about.p3': 'Меня вдохновляет делать знания доступными и полезными для всех.',
    'about.highlights': 'Ключевые качества:',
    'about.desiredTitle': 'Желаемая позиция',
    'about.desiredPosition': 'Руководитель цифровых знаний / Контент-стратег',
    'about.employment': 'Полная занятость, удалённо или гибрид, проектная работа.',
    
    // Skills Section
    'skills.title': 'Ключевые компетенции',
    'skills.subtitle': 'Профессиональные навыки и экспертиза в различных областях',
    'skills.professional': 'Профессиональные навыки',
    'skills.technical': 'Технические компетенции',
    'skills.languages': 'Языковые навыки',
    'skills.projectManagement': 'Управление проектами',
    'skills.contentStrategy': 'Контент-стратегия',
    'skills.productThinking': 'Продуктовое мышление',
    'skills.dataAnalytics': 'Аналитика данных',
    'skills.systemThinking': 'Системное мышление',
    'skills.teamManagement': 'Управление командой',
    'skills.analytics': 'Аналитика',
    'skills.projectManagementCat': 'Управление проектами',
    'skills.contentCreation': 'Создание контента',
    'skills.automation': 'Автоматизация',
    'skills.processes': 'Процессы',
    'skills.systems': 'Системы',
    'skills.documentation': 'Документация',
    'skills.russian': 'Русский',
    'skills.english': 'Английский',
    'skills.french': 'Французский',
    'skills.native': 'Родной',
    'skills.digitalLibraries': 'Цифровые библиотеки',
    'skills.userExperience': 'Пользовательский опыт',
    'skills.informationArchitecture': 'Информационная архитектура',
    'skills.digitalTransformation': 'Цифровая трансформация',
    
    // Experience Section
    'experience.title': 'Профессиональный опыт',
    'experience.company': 'Российская государственная библиотека',
    'experience.position': 'Главный редактор мобильного приложения «Свет»',
    'experience.location': 'Москва',
    'experience.period': 'Февраль 2022 — Январь 2025',
    'experience.description': 'Возглавляла продуктовую команду, отвечающую за контент, аналитику и развитие цифрового сервиса для миллионов пользователей.',
    'experience.achievements': 'Ключевые достижения:',
    'experience.ach1': 'Увеличила KPI (книговыдачи) в 3 раза (до 2,5-3 млн в год) за счет стратегии контента, партнерств и аналитики',
    'experience.ach2': 'Разработала и координировала 17 крупных партнерских проектов',
    'experience.ach3': 'Сотрудничество с Московской электронной школой — 3 млн потенциальных пользователей, 100 тыс. книговыдач в 2024',
    'experience.ach4': 'Акция «Лето с Пятерочкой» — охват 1350 магазинов, рост переходов на сайт в 10 раз за месяц',
    'experience.ach5': 'Построила систему сбора и визуализации данных (Яндекс.Метрика, Superset, Excel)',
    'experience.ach6': 'Создала внутренние сервисы для автоматизации — сокращение времени подготовки текстов с 2 дней до 30 минут',
    'experience.ach7': 'Перевела команду на российский инструмент (Kaiten), создав систему контроля процессов',
    'experience.ach8': 'Разработала 11 лендингов в Tilda',
    'experience.ach9': 'Управляла редакцией из 5 человек',
    'experience.current': 'Текущий',
    
    // Education Section
    'education.title': 'Образование и повышение квалификации',
    'education.education': 'Образование',
    'education.certifications': 'Повышение квалификации',
    'education.degree1': 'Магистр журналистики',
    'education.institution1': 'Московский государственный университет им. М.В. Ломоносова',
    'education.program1': 'Международная программа: Mastère franco-russe de journalisme',
    'education.degree2': 'Филология',
    'education.institution2': 'Новосибирский национальный исследовательский государственный университет',
    'education.cert1': 'Сертифицированный Agile-профессионал',
    'education.cert2': 'Продуктовая аналитика',
    'education.cert3': 'Гибкая разработка (Agile) с Jira',
    'education.cert4': 'Авторское право',
    'education.certOrg4': 'ВОИС',
    'education.cert5': 'Инструменты анализа данных',
    'education.certOrg5': 'Яндекс Практикум',
    'education.cert6': 'Менеджер проектов',
    'education.certOrg6': 'Яндекс Практикум',
    'education.cert7': 'Контент-маркетинг',
    'education.certOrg7': 'Нетология',
    
    // Portfolio Section
    'portfolio.title': 'Портфолио',
    'portfolio.subtitle': 'Примеры моих проектов: от лендингов и промо-сайтов до инструкций и дизайн-системы',
    'portfolio.landingProjects': 'Лендинги спецпроектов',
    'portfolio.texts': 'Тексты и фотографии',
    'portfolio.loveBooks': 'Книги о счастливой любви',
    'portfolio.loveBooksDesc': 'Тематический лендинг для продвижения коллекции книг о любви',
    'portfolio.readingInSky': 'Читаем в небе',
    'portfolio.readingInSkyDesc': 'Промо-сайт проекта совместного чтения',
    'portfolio.gamzatov100': '100 лет Расулу Гамзатову',
    'portfolio.gamzatov100Desc': 'Юбилейный проект к столетию поэта',
    'portfolio.newYear2025': 'Новогодние предсказания',
    'portfolio.newYear2025Desc': 'Интерактивный новогодний проект',
    'portfolio.pushkin225': 'Квиз к 225-летию А.С. Пушкина',
    'portfolio.pushkin225Desc': 'Онлайн-викторина к юбилею великого поэта',
    'portfolio.posters': 'Плакаты и раздатки',
    'portfolio.pushkinColoring': 'Раскраски к юбилею А.С. Пушкина',
    'portfolio.pushkinColoringDesc': 'Детские раскраски для популяризации творчества поэта',
    'portfolio.newYearDecorations': 'Новогодние украшения с символикой проекта',
    'portfolio.newYearDecorationsDesc': 'Брендированные новогодние материалы',
    'portfolio.libraryInfographics': 'Инфографика для библиотек',
    'portfolio.libraryInfographicsDesc': 'Информационные материалы для партнерских библиотек',
    'portfolio.manuals': 'Инструкции и руководства',
    'portfolio.mobileLibraries2024': 'Руководство для мобильных библиотек 2024',
    'portfolio.mobileLibraries2024Desc': 'Подробные инструкции для работы с мобильными библиотеками',
    'portfolio.brandedIllustrations': 'Макеты брендированных иллюстраций',
    'portfolio.brandedIllustrationsDesc': 'Figma-макеты для создания плакатов в едином стиле проекта',
    'portfolio.digitalMerch': 'Цифровой мерч',
    'portfolio.telegramStickers': 'Стикеры для Telegram',
    'portfolio.telegramStickersDesc': 'Набор брендированных стикеров для мессенджера Telegram',
    'portfolio.additionalMaterials': 'Дополнительные материалы',
    'portfolio.githubProfile': 'GitHub профиль',
    'portfolio.texts1': 'Дни культуры Таджикистана в РГБ',
    'portfolio.texts1Desc': 'Репортаж с открытия двух выставок, приуроченных к Дням культуры Республики Таджикистан в России.',
    'portfolio.texts1Url': 'https://www.rsl.ru/ru/events/afisha/vistavki/dni-kultury-tadzhikistana-v-rgb',
    'portfolio.texts2': 'XVIII Международные научные чтения памяти Николая Фёдоровича Фёдорова',
    'portfolio.texts2Desc': 'Торжественное открытие XVIII Международных научных чтений памяти философа Н. Ф. Фёдорова.',
    'portfolio.texts2Url': 'https://www.rsl.ru/ru/all-news/xviii-fedorovskie-chtenia',
    'portfolio.texts3': 'Круглый стол «Уникальный лингвистический фонд коренных народов cеверных территорий — мировая сокровищница культуры»',
    'portfolio.texts3Desc': 'Круглый стол, посвящённый Международному году языков коренных народов Севера.',
    'portfolio.texts3Url': 'https://www.rsl.ru/ru/events/afisha/meetings/kruglyij-stol-unikalnyij-lingvisticheskij-fond',
    'portfolio.texts4': 'Круглый стол «День ООН в РГБ — 2019»',
    'portfolio.texts4Desc': 'Круглый стол, посвящённый Дню ООН и 74-й сессии Генеральной Ассамблеи ООН.',
    'portfolio.texts4Url': 'https://www.rsl.ru/ru/events/afisha/meetings/kruglyij-stol-den-oon-v-rgb-2019',
    'portfolio.texts5': 'В РГБ открылась фотовыставка пейзажей Южного берега Крыма',
    'portfolio.texts5Desc': 'Торжественное открытие баннерной выставки «Берег мечты. Культурное и природное наследие Южного берега Крыма».',
    'portfolio.texts5Url': 'https://www.rsl.ru/ru/all-news/fotovyistavka-pejzazhej-yuzhnogo-berega-kryima',
    'portfolio.texts6': 'Понаснимали тут',
    'portfolio.texts6Desc': 'Стартовал «анонимный» этап конкурса на лучший фоторепортаж о Москве «Серебряная камера-2005».',
    'portfolio.texts6Url': 'https://web.archive.org/web/20061130092311/http://lenta.ru:80/articles/2006/10/03/foto/',
    'portfolio.texts7': 'И уэльбекерно, и тошно',
    'portfolio.texts7Desc': 'Скандальный французский писатель привез в Россию новый роман',
    'portfolio.texts7Url': 'https://web.archive.org/web/20120214221335/http://lenta.ru:80/articles/2006/04/20/houellebecq/',
    'portfolio.texts8': '«Надеюсь, вы не купили мою книгу»',
    'portfolio.texts8Desc': 'Фредерик Бегбедер прилетел на свидание с Москвой',
    'portfolio.texts8Url': 'https://web.archive.org/web/20120708064328/http://lenta.ru/articles/2006/07/03/beigbeder/',
    'portfolio.texts9': 'Свидание с Ктулху',
    'portfolio.texts9Desc': 'Роман про морских чудищ захватил книжные витрины',
    'portfolio.texts9Url': 'https://disk.yandex.ru/i/5dekldkfLa54dA',
    'portfolio.texts10': 'Юлия Наполова: «Буквы остаются в музее»',
    'portfolio.texts10Desc': 'Интервью с дизайнером выставки «Время собирать… Князь Юсупов и его библиотека»',
    'portfolio.texts10Url': 'https://www.rsl.ru/ru/all-news/julia-napolova-interview',
    
    // Graphic Design Portfolio
    'portfolio.graphicDesign': 'Графический дизайн',
    'portfolio.socialIllustrations': 'Иллюстрации для соцсетей',
    'portfolio.socialIllustrationsDesc': 'Коллекция иллюстраций для постов в социальных сетях и рекламных материалов',
    'portfolio.bookCovers': 'Книжные обложки',
    'portfolio.bookCoversDesc': 'Креативные дизайны обложек книг с современной типографикой и визуальными элементами',
    'portfolio.postersAndDiplomas': 'Постеры и дипломы',
    'portfolio.postersAndDiplomasDesc': 'Постеры для мероприятий, сертификаты и дипломы для различных организаций',
    'portfolio.designProjects': 'Дизайн-проекты',
    'portfolio.printMaterials': 'Печатные материалы',
    'portfolio.digitalDesign': 'Цифровой дизайн',
    
    // Contact Section
    'contact.title': 'Свяжитесь со мной',
    'contact.phone': 'Телефон',
    'contact.email': 'Email',
    'contact.telegram': 'Telegram',
    'contact.linkedin': 'LinkedIn',
    'contact.footer': '2025 год • Ольга Морозова • Создано в Make',
    
    // Case Studies Section
    'cases.title': 'Кейсы',
    'cases.subtitle': 'Реальные проекты с измеримыми результатами и бизнес-эффектом',
    
    // Aeroflot Case
    'cases.aeroflot.title': 'Аудиокниги на борту Аэрофлота',
    'cases.aeroflot.backgroundTitle': 'Задача',
    'cases.aeroflot.background': 'Аэрофлот, ведущая российская авиакомпания, хотела улучшить впечатления пассажиров в полете с помощью увлекательного цифрового контента. В рамках партнерства между Аэрофлотом и Российской государственной библиотекой мы разработали мультимедийный сервис аудиокниг, доступный на борту.',
    'cases.aeroflot.roleTitle': 'Моя роль',
    'cases.aeroflot.role1': 'Курировала контент: отобрала и организовала коллекцию аудиокниг, адаптированную для аудитории авиапассажиров',
    'cases.aeroflot.role2': 'Разработала стандарты дизайна контента: создала обложки аудиокниг с использованием ИИ-генерации',
    'cases.aeroflot.role3': 'Координировала интеграцию контента: согласовала стандарты публикации для приложения Аэрофлота и лендинга проекта',
    'cases.aeroflot.role4': 'Взаимодействовала с техническими командами для обеспечения плавной доставки и доступности',
    'cases.aeroflot.processTitle': 'Процесс',
    'cases.aeroflot.process1': 'Исследовала предпочтения пассажиров по контенту и определила разнообразную подборку аудиокниг',
    'cases.aeroflot.process2': 'Создала рабочий процесс производства контента, включая дизайн обложек, подготовку метаданных и форматирование',
    'cases.aeroflot.process3': 'Создала отдельный лендинг для продвижения и удобства навигации',
    'cases.aeroflot.process4': 'Применила ИИ-инструменты для создания цельных и привлекательных дизайнов обложек, обеспечив современную, инновационную эстетику',
    'cases.aeroflot.resultsTitle': 'Результаты',
    'cases.aeroflot.result1': 'Успешно запустила новую функцию цифровых развлечений для пассажиров Аэрофлота',
    'cases.aeroflot.result2': 'Проект был представлен Министру культуры и заместителю Министра образования, получил официальное одобрение и положительную оценку',
    'cases.aeroflot.result3': 'Укрепила позиционирование Аэрофлота как новатора в области пассажирского опыта',
    'cases.aeroflot.result4': 'Продемонстрировала потенциал интеграции ИИ-дизайна в масштабные культурные и коммерческие проекты',
    'cases.aeroflot.highlightsTitle': 'Ключевые достижения',
    'cases.aeroflot.highlight1': 'Корпоративное партнерство с национальной авиакомпанией',
    'cases.aeroflot.highlight2': 'Инновации в дизайне с использованием ИИ',
    'cases.aeroflot.highlight3': 'Высокая оценка государственных чиновников',
    'cases.aeroflot.highlight4': 'Кросс-функциональное управление проектами (контент, дизайн, техническая интеграция)',
    
    // MESH Case
    'cases.mesh.title': 'Интеграция с Московской электронной школой',
    'cases.mesh.backgroundTitle': 'Задача',
    'cases.mesh.background': 'Московская электронная школа (МЭШ) — одна из крупнейших образовательных цифровых платформ России, предоставляющая миллионам учеников и учителей доступ к учебным ресурсам. Российская государственная библиотека стремилась интегрировать свой цифровой каталог в МЭШ для обеспечения бесплатного доступа к важнейшим литературным произведениям школьной программы.',
    'cases.mesh.roleTitle': 'Моя роль',
    'cases.mesh.role1': 'Координировала интеграцию нашей цифровой библиотеки с МЭШ через API',
    'cases.mesh.role2': 'Отбирала и курировала каталог книг в соответствии с школьными программами',
    'cases.mesh.role3': 'Контролировала подготовку контента, включая метаданные, аннотации и форматирование',
    'cases.mesh.role4': 'Выступала связующим звеном между разработчиками, редакторами и образовательными заинтересованными сторонами',
    'cases.mesh.processTitle': 'Процесс',
    'cases.mesh.process1': 'Определила технические требования и координировала внедрение API с командой разработки',
    'cases.mesh.process2': 'Управляла редакционным процессом для обеспечения точности и соответствия образовательным стандартам',
    'cases.mesh.process3': 'Контролировала обеспечение качества доставки контента и доступности для пользователей',
    'cases.mesh.process4': 'Взаимодействовала с образовательными партнерами для согласования контента с потребностями преподавания',
    'cases.mesh.resultsTitle': 'Результаты',
    'cases.mesh.result1': 'Успешно интегрировала тысячи книг в экосистему МЭШ',
    'cases.mesh.result2': 'Обеспечила бесплатный доступ к литературе для более чем 1 миллиона учеников и учителей',
    'cases.mesh.result3': 'Повысила образовательную ценность платформы, согласовав контент с официальными учебными программами',
    'cases.mesh.result4': 'Укрепила роль библиотеки как национального лидера в области цифровых образовательных инициатив',
    'cases.mesh.highlightsTitle': 'Ключевые достижения',
    'cases.mesh.highlight1': 'Крупномасштабное B2B партнерство в образовании',
    'cases.mesh.highlight2': 'API-интеграция с крупной цифровой платформой',
    'cases.mesh.highlight3': 'Прямое социальное воздействие: более 1 млн учеников и учителей',
    'cases.mesh.highlight4': 'Экспертиза в координации технических и редакционных команд',
    
    // Metro Case
    'cases.metro.title': 'Московское метро «Подземный читальный зал»',
    'cases.metro.backgroundTitle': 'Задача',
    'cases.metro.background': 'Московский метрополитен, одна из самых загруженных систем общественного транспорта в мире, хотел вовлечь пассажиров в культурные инициативы. Совместно с Российской государственной библиотекой мы превратили одну из станций метро в интерактивный «Подземный читальный зал», позволяющий пассажирам получать доступ к подобранным книгам через QR-коды.',
    'cases.metro.roleTitle': 'Моя роль',
    'cases.metro.role1': 'Разработала концепцию контента и курировала цифровую библиотеку для проекта',
    'cases.metro.role2': 'Спроектировала механику доступа через QR-коды, обеспечивая удобный пользовательский опыт',
    'cases.metro.role3': 'Координировала работу с властями метрополитена и техническими командами по внедрению',
    'cases.metro.role4': 'Контролировала создание коммуникационных материалов и руководства для пользователей',
    'cases.metro.processTitle': 'Процесс',
    'cases.metro.process1': 'Отобрала разнообразную коллекцию книг, адаптированную для коротких и длинных поездок',
    'cases.metro.process2': 'Создала систему QR-кодов, размещенных по всей станции и ведущих напрямую к ресурсам библиотеки',
    'cases.metro.process3': 'Обеспечила техническую функциональность и доступность ссылок на всех устройствах',
    'cases.metro.process4': 'Отслеживала взаимодействие пользователей и упоминания в СМИ для оценки вовлеченности',
    'cases.metro.resultsTitle': 'Результаты',
    'cases.metro.result1': 'Запустила первую интерактивную культурную инициативу в Московском метро',
    'cases.metro.result2': 'Превратила узел общественного транспорта в брендированный культурный опыт',
    'cases.metro.result3': 'Привлекла широкое внимание СМИ и получила положительные отзывы от пассажиров',
    'cases.metro.result4': 'Укрепила имидж библиотеки как новатора в области цифрового взаимодействия',
    'cases.metro.highlightsTitle': 'Ключевые достижения',
    'cases.metro.highlight1': 'Креативное использование QR-технологий для культурного взаимодействия',
    'cases.metro.highlight2': 'Высокотрафиковая городская среда (тысячи пассажиров ежедневно)',
    'cases.metro.highlight3': 'Позитивный пользовательский опыт и освещение в СМИ',
    'cases.metro.highlight4': 'Успешное сотрудничество с государственными органами',
    
    // Pushkin Case
    'cases.pushkin.title': 'Проект к юбилею Александра Пушкина',
    'cases.pushkin.backgroundTitle': 'Задача',
    'cases.pushkin.background': 'К юбилею Александра Пушкина Российская государственная библиотека инициировала масштабный гибридный проект для вовлечения как онлайн, так и офлайн аудитории. Инициатива была направлена на продвижение классической литературы в современном интерактивном формате.',
    'cases.pushkin.roleTitle': 'Моя роль',
    'cases.pushkin.role1': 'Разработала общую концепцию контента и структуру викторины',
    'cases.pushkin.role2': 'Создала контент в разных форматах: викторины, печатные материалы, стикеры и раскраски',
    'cases.pushkin.role3': 'Координировала участие по всей стране, работая со 140 библиотеками в 50 регионах',
    'cases.pushkin.role4': 'Руководила онлайн и офлайн распространением контента и мероприятий',
    'cases.pushkin.processTitle': 'Процесс',
    'cases.pushkin.process1': 'Разработала увлекательные вопросы викторины для различных аудиторий',
    'cases.pushkin.process2': 'Подготовила дизайн-материалы для цифрового и физического участия',
    'cases.pushkin.process3': 'Создала руководства и коммуникационные наборы для региональных библиотек',
    'cases.pushkin.process4': 'Организовала обратную связь для обеспечения плавного внедрения во всех регионах',
    'cases.pushkin.resultsTitle': 'Результаты',
    'cases.pushkin.result1': 'Успешное общенациональное гибридное мероприятие с участием 140 библиотек в 50 регионах',
    'cases.pushkin.result2': 'Тысячи участников вовлечены через онлайн и офлайн каналы',
    'cases.pushkin.result3': 'Повышена видимость классической литературы среди молодой аудитории',
    'cases.pushkin.result4': 'Признание профессионального сообщества через презентации на конференциях',
    'cases.pushkin.highlightsTitle': 'Ключевые достижения',
    'cases.pushkin.highlight1': 'Контент-операции в масштабе (многоформатные активы, многоканальное распространение)',
    'cases.pushkin.highlight2': 'Крупномасштабная координация с десятками региональных партнеров',
    'cases.pushkin.highlight3': 'Продемонстрированная способность управлять гибридными проектами (онлайн + офлайн)',
    'cases.pushkin.highlight4': 'Продвижение культурного наследия через инновационные методы взаимодействия',
    
    // PDF Export
    'pdf.button': 'Скачать резюме в DOCX',
    'pdf.description': 'Полное резюме в формате DOCX',
    'pdf.generating': 'Генерирую...',
    'pdf.error': 'Произошла ошибка при создании DOCX. Попробуйте еще раз.',
    
    // Case Studies buttons
    'cases.showDetails': 'Показать детали',
    'cases.hideDetails': 'Скрыть детали',
  } as const,
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.experience': 'Expérience',
    'nav.skills': 'Compétences',
    'nav.cases': 'Études de cas',
    'nav.portfolio': 'Portfolio',
    'nav.education': 'Formation',
    'nav.contact': 'Contact',

    // Hero Section
    'hero.title': 'Olga Morozova',
    'hero.subtitle': 'Directrice de contenu numérique',
    'hero.description': 'Spécialisée dans la stratégie de contenu numérique, la gestion de projet et les initiatives culturelles innovantes',

    // About Section
    'about.title': 'À propos de moi',
    'about.text1': 'Directrice de contenu numérique expérimentée avec plus de 7 ans d\'expertise dans la gestion de contenu numérique, la stratégie et l\'innovation dans le secteur culturel.',
    'about.text2': 'J\'ai dirigé avec succès des projets transformationnels à la Bibliothèque d\'État russe, gérant des initiatives numériques à grande échelle et favorisant des partenariats stratégiques.',
    'about.text3': 'Ma passion réside dans l\'intersection de la technologie et de la culture, créant des expériences numériques engageantes qui rendent le patrimoine culturel accessible aux audiences modernes.',
    'about.highlights': 'Qualités clés :',

    // Experience Section
    'experience.title': 'Expérience professionnelle',
    'experience.russian-state-library.title': 'Bibliothèque d\'État russe',
    'experience.russian-state-library.position': 'Directrice de contenu numérique',
    'experience.russian-state-library.period': '2017 - Présent',
    'experience.russian-state-library.description': 'Direction des initiatives de contenu numérique, gestion d\'équipes inter-fonctionnelles et développement de partenariats stratégiques dans le secteur culturel.',

    'experience.responsibilities.content-strategy': 'Stratégie de contenu',
    'experience.responsibilities.team-management': 'Gestion d\'équipe',
    'experience.responsibilities.project-leadership': 'Leadership de projet',
    'experience.responsibilities.partnership-development': 'Développement de partenariats',

    // Skills Section
    'skills.title': 'Compétences',
    'skills.content-management': 'Gestion de contenu',
    'skills.digital-strategy': 'Stratégie numérique',
    'skills.project-management': 'Gestion de projet',
    'skills.team-leadership': 'Leadership d\'équipe',
    'skills.cultural-projects': 'Projets culturels',
    'skills.partnership-development': 'Développement de partenariats',
    'skills.russian': 'Russe',
    'skills.english': 'Anglais',
    'skills.french': 'Français',

    // Portfolio Section
    'portfolio.title': 'Portfolio',
    'portfolio.view-case': 'Voir l\'étude de cas',
    'portfolio.texts1': 'Journées de la culture du Tadjikistan à la RSL',
    'portfolio.texts1Desc': 'Reportage de l\'ouverture de deux expositions consacrées aux Journées de la culture de la République du Tadjikistan en Russie.',
    'portfolio.texts1Url': 'https://www.rsl.ru/ru/events/afisha/vistavki/dni-kultury-tadzhikistana-v-rgb',
    'portfolio.texts2': 'XVIIIe Lectures scientifiques internationales en mémoire de Nikolaï Fedorov',
    'portfolio.texts2Desc': 'Ouverture solennelle des XVIIIe Lectures scientifiques internationales en mémoire du philosophe N. F. Fedorov.',
    'portfolio.texts2Url': 'https://www.rsl.ru/ru/all-news/xviii-fedorovskie-chtenia',
    'portfolio.texts3': 'Table ronde « Patrimoine linguistique unique des peuples autochtones du Nord »',
    'portfolio.texts3Desc': 'Table ronde consacrée à l\'Année internationale des langues des peuples autochtones du Nord.',
    'portfolio.texts3Url': 'https://www.rsl.ru/ru/events/afisha/meetings/kruglyij-stol-unikalnyij-lingvisticheskij-fond',
    'portfolio.texts4': 'Table ronde « Journée de l\'ONU à la RSL — 2019 »',
    'portfolio.texts4Desc': 'Table ronde consacrée à la Journée de l\'ONU et à la 74e session de l\'Assemblée générale de l\'ONU.',
    'portfolio.texts4Url': 'https://www.rsl.ru/ru/events/afisha/meetings/kruglyij-stol-den-oon-v-rgb-2019',
    'portfolio.texts5': 'Exposition de photos de paysages de la côte sud de la Crimée à la RSL',
    'portfolio.texts5Desc': 'Ouverture de l\'exposition de bannières « Côte de rêve. Patrimoine culturel et naturel de la côte sud de la Crimée ».',
    'portfolio.texts5Url': 'https://www.rsl.ru/ru/all-news/fotovyistavka-pejzazhej-yuzhnogo-berega-kryima',
    'portfolio.texts6': 'Prise de photos',
    'portfolio.texts6Desc': 'L\'étape « anonyme » du concours du meilleur reportage photo sur Moscou « Caméra d\'argent-2005 » a commencé.',
    'portfolio.texts6Url': 'https://web.archive.org/web/20061130092311/http://lenta.ru:80/articles/2006/10/03/foto/',
    'portfolio.texts7': 'À la fois houellebecquien et écœurant',
    'portfolio.texts7Desc': 'L\'écrivain français scandaleux a apporté un nouveau roman en Russie',
    'portfolio.texts7Url': 'https://web.archive.org/web/20120214221335/http://lenta.ru:80/articles/2006/04/20/houellebecq/',
    'portfolio.texts8': '« J\'espère que vous n\'avez pas acheté mon livre »',
    'portfolio.texts8Desc': 'Frédéric Beigbeder s\'est envolé pour un rendez-vous avec Moscou',
    'portfolio.texts8Url': 'https://web.archive.org/web/20120708064328/http://lenta.ru/articles/2006/07/03/beigbeder/',
    'portfolio.texts9': 'Rendez-vous avec Cthulhu',
    'portfolio.texts9Desc': 'Un roman sur les monstres marins a capturé les vitrines des librairies',
    'portfolio.texts9Url': 'https://disk.yandex.ru/i/5dekldkfLa54dA',
    'portfolio.texts10': 'Julia Napolova : « Les lettres restent au musée »',
    'portfolio.texts10Desc': 'Interview avec la designer de l’exposition « Le temps de rassembler… Le prince Youssoupov et sa bibliothèque »',
    'portfolio.texts10Url': 'https://www.rsl.ru/ru/all-news/julia-napolova-interview',
    
    // Graphic Design Portfolio
    'portfolio.graphicDesign': 'Design Graphique',
    'portfolio.socialIllustrations': 'Illustrations pour les Réseaux Sociaux',
    'portfolio.socialIllustrationsDesc': 'Collection d\'illustrations pour les publications sur les réseaux sociaux et matériaux promotionnels',
    'portfolio.bookCovers': 'Couvertures de Livres',
    'portfolio.bookCoversDesc': 'Designs créatifs de couvertures de livres avec typographie moderne et éléments visuels',
    'portfolio.postersAndDiplomas': 'Affiches et Diplômes',
    'portfolio.postersAndDiplomasDesc': 'Affiches d\'événements, certificats et diplômes pour diverses organisations',

    // Education Section
    'education.title': 'Formation',
    'education.msu.degree': 'Master en Journalisme',
    'education.msu.institution': 'Université d\'État de Moscou',
    'education.msu.period': '2013 - 2017',
    'education.msu.description': 'Spécialisée en journalisme numérique et communication de masse avec mention.',

    // Contact Section
    'contact.title': 'Contact',
    'contact.email': 'Email',
    'contact.phone': 'Téléphone',
    'contact.location': 'Lieu',
    'contact.moscow': 'Moscou, Russie',

    // Cases Section
    'cases.title': 'Études de cas',
    'cases.subtitle': 'Découvrez quelques-uns de mes projets les plus impactants dans la transformation numérique culturelle',

    // Aeroflot Case
    'cases.aeroflot.title': 'Partenariat avec Aéroflot : Design généré par IA',
    'cases.aeroflot.backgroundTitle': 'Contexte',
    'cases.aeroflot.background': 'Aéroflot, la compagnie aérienne phare de la Russie, cherchait à améliorer l\'expérience passager grâce à des initiatives culturelles innovantes. En partenariat avec la Bibliothèque d\'État russe, nous avons développé un système de design généré par IA qui créait des motifs visuels uniques basés sur la littérature russe classique pour les intérieurs d\'avion.',
    'cases.aeroflot.roleTitle': 'Mon rôle',
    'cases.aeroflot.role1': 'J\'ai dirigé la stratégie de contenu et la curation pour l\'intégration littéraire',
    'cases.aeroflot.role2': 'J\'ai collaboré avec les équipes de design IA pour développer les algorithmes de génération de motifs',
    'cases.aeroflot.role3': 'J\'ai géré les relations avec les parties prenantes entre la bibliothèque, Aéroflot et les partenaires technologiques',
    'cases.aeroflot.role4': 'J\'ai supervisé la mise en œuvre du projet du concept à l\'exécution',
    'cases.aeroflot.processTitle': 'Processus',
    'cases.aeroflot.process1': 'J\'ai analysé la littérature russe classique pour identifier les éléments visuels et thématiques',
    'cases.aeroflot.process2': 'J\'ai développé des algorithmes avec l\'équipe technique pour traduire les thèmes littéraires en motifs de design',
    'cases.aeroflot.process3': 'J\'ai testé et affiné les sorties IA pour s\'aligner avec l\'identité de marque d\'Aéroflot',
    'cases.aeroflot.process4': 'J\'ai coordonné l\'installation pilote et recueilli les retours pour des améliorations itératives',
    'cases.aeroflot.resultsTitle': 'Résultats',
    'cases.aeroflot.result1': 'Lancement réussi de la première initiative de design généré par IA dans l\'aviation commerciale russe',
    'cases.aeroflot.result2': 'Retours positifs des passagers et reconnaissance de l\'industrie pour l\'innovation',
    'cases.aeroflot.result3': 'Renforcement du positionnement d\'Aéroflot comme innovateur dans l\'expérience passager',
    'cases.aeroflot.result4': 'Démonstration du potentiel de l\'intégration du design IA dans les projets culturels et commerciaux à grande échelle',
    'cases.aeroflot.highlightsTitle': 'Points clés',
    'cases.aeroflot.highlight1': 'Partenariat d\'entreprise avec la compagnie aérienne nationale',
    'cases.aeroflot.highlight2': 'Innovation en design avec l\'utilisation de l\'IA',
    'cases.aeroflot.highlight3': 'Reconnaissance de haut niveau par les officiels gouvernementaux',
    'cases.aeroflot.highlight4': 'Gestion de projet inter-fonctionnelle (contenu, design, intégration technique)',

    // MESH Case
    'cases.mesh.title': 'Intégration avec l\'École électronique de Moscou',
    'cases.mesh.backgroundTitle': 'Contexte',
    'cases.mesh.background': 'L\'École électronique de Moscou (MES) est l\'une des plus grandes plateformes éducatives numériques de Russie, fournissant l\'accès aux ressources d\'apprentissage à des millions d\'étudiants et d\'enseignants. La Bibliothèque d\'État russe cherchait à intégrer son catalogue numérique dans MES pour fournir un accès gratuit aux œuvres littéraires essentielles du programme scolaire.',
    'cases.mesh.roleTitle': 'Mon rôle',
    'cases.mesh.role1': 'J\'ai coordonné l\'intégration de notre bibliothèque numérique avec MES via API',
    'cases.mesh.role2': 'J\'ai sélectionné et curé le catalogue de livres selon les programmes scolaires',
    'cases.mesh.role3': 'J\'ai supervisé la préparation du contenu, incluant les métadonnées, annotations et formatage',
    'cases.mesh.role4': 'J\'ai servi de liaison entre les développeurs, éditeurs et parties prenantes éducatives',
    'cases.mesh.processTitle': 'Processus',
    'cases.mesh.process1': 'J\'ai défini les exigences techniques et coordonné la mise en œuvre API avec l\'équipe de développement',
    'cases.mesh.process2': 'J\'ai géré le processus éditorial pour assurer l\'exactitude et la conformité aux standards éducatifs',
    'cases.mesh.process3': 'J\'ai supervisé l\'assurance qualité pour la livraison de contenu et l\'accessibilité utilisateur',
    'cases.mesh.process4': 'J\'ai collaboré avec les partenaires éducatifs pour aligner le contenu avec les besoins d\'enseignement',
    'cases.mesh.resultsTitle': 'Résultats',
    'cases.mesh.result1': 'Intégration réussie de milliers de livres dans l\'écosystème MES',
    'cases.mesh.result2': 'Fourniture d\'un accès gratuit à la littérature pour plus d\'1 million d\'étudiants et d\'enseignants',
    'cases.mesh.result3': 'Amélioration de la valeur éducative de la plateforme en alignant le contenu avec les programmes officiels',
    'cases.mesh.result4': 'Renforcement du rôle de la bibliothèque comme leader national dans les initiatives éducatives numériques',
    'cases.mesh.highlightsTitle': 'Points clés',
    'cases.mesh.highlight1': 'Partenariat B2B éducatif à grande échelle',
    'cases.mesh.highlight2': 'Intégration pilotée par API avec une plateforme numérique majeure',
    'cases.mesh.highlight3': 'Impact social direct : plus d\'1 million d\'étudiants et d\'enseignants touchés',
    'cases.mesh.highlight4': 'Expertise en coordination d\'équipes techniques et éditoriales',

    // Metro Case
    'cases.metro.title': 'Métro de Moscou « Salle de lecture souterraine »',
    'cases.metro.backgroundTitle': 'Contexte',
    'cases.metro.background': 'Le métro de Moscou, l\'un des systèmes de transport public les plus fréquentés au monde, souhaitait engager les passagers avec des initiatives culturelles. En collaboration avec la Bibliothèque d\'État russe, nous avons transformé l\'une des stations de métro en « Salle de lecture souterraine » interactive, permettant aux passagers d\'accéder aux livres sélectionnés via des codes QR.',
    'cases.metro.roleTitle': 'Mon rôle',
    'cases.metro.role1': 'J\'ai développé le concept de contenu et curé la bibliothèque numérique pour le projet',
    'cases.metro.role2': 'J\'ai conçu la mécanique d\'accès par code QR, assurant une expérience utilisateur fluide',
    'cases.metro.role3': 'J\'ai coordonné avec les autorités du métro et les équipes techniques pour la mise en œuvre',
    'cases.metro.role4': 'J\'ai supervisé les matériaux de communication et les guides utilisateur',
    'cases.metro.processTitle': 'Processus',
    'cases.metro.process1': 'J\'ai sélectionné une collection diversifiée de livres adaptés aux trajets courts et longs',
    'cases.metro.process2': 'J\'ai créé un système de codes QR placés dans toute la station, reliant directement aux ressources de la bibliothèque',
    'cases.metro.process3': 'J\'ai assuré la fonctionnalité technique et l\'accessibilité des liens sur tous les appareils',
    'cases.metro.process4': 'J\'ai surveillé les interactions utilisateur et les mentions médiatiques pour mesurer l\'engagement',
    'cases.metro.resultsTitle': 'Résultats',
    'cases.metro.result1': 'Lancement de la première initiative culturelle interactive dans le métro de Moscou',
    'cases.metro.result2': 'Transformation d\'un hub de transport public en expérience culturelle de marque',
    'cases.metro.result3': 'Génération d\'une large attention médiatique et de retours positifs des passagers',
    'cases.metro.result4': 'Renforcement de l\'image de la bibliothèque comme innovateur dans l\'engagement numérique',
    'cases.metro.highlightsTitle': 'Points clés',
    'cases.metro.highlight1': 'Utilisation créative de la technologie QR pour l\'engagement culturel',
    'cases.metro.highlight2': 'Environnement urbain à fort trafic (milliers de passagers quotidiens)',
    'cases.metro.highlight3': 'Expérience utilisateur positive et couverture médiatique',
    'cases.metro.highlight4': 'Collaboration réussie avec les autorités publiques',

    // Pushkin Case
    'cases.pushkin.title': 'Projet anniversaire d\'Alexandre Pouchkine',
    'cases.pushkin.backgroundTitle': 'Contexte',
    'cases.pushkin.background': 'Pour célébrer l\'anniversaire d\'Alexandre Pouchkine, la Bibliothèque d\'État russe a initié un projet hybride à grande échelle pour engager les audiences en ligne et hors ligne. L\'initiative visait à promouvoir la littérature classique dans un format moderne et interactif.',
    'cases.pushkin.roleTitle': 'Mon rôle',
    'cases.pushkin.role1': 'J\'ai conçu le concept de contenu global et la structure du quiz',
    'cases.pushkin.role2': 'J\'ai produit du contenu multi-format : quiz, matériaux imprimables, autocollants et livres de coloriage',
    'cases.pushkin.role3': 'J\'ai coordonné la participation nationale, travaillant avec 140 bibliothèques dans 50 régions',
    'cases.pushkin.role4': 'J\'ai dirigé la distribution en ligne et hors ligne du contenu et des activités',
    'cases.pushkin.processTitle': 'Processus',
    'cases.pushkin.process1': 'J\'ai développé des questions de quiz engageantes adaptées à diverses audiences',
    'cases.pushkin.process2': 'J\'ai préparé des éléments de design pour la participation numérique et physique',
    'cases.pushkin.process3': 'J\'ai créé des guides et des kits de communication pour les bibliothèques régionales',
    'cases.pushkin.process4': 'J\'ai géré la boucle de retour pour assurer un déploiement fluide dans toutes les régions',
    'cases.pushkin.resultsTitle': 'Résultats',
    'cases.pushkin.result1': 'Événement hybride national réussi impliquant 140 bibliothèques dans 50 régions',
    'cases.pushkin.result2': 'Milliers de participants engagés via les canaux en ligne et hors ligne',
    'cases.pushkin.result3': 'Visibilité accrue de la littérature classique parmi les jeunes audiences',
    'cases.pushkin.result4': 'Reconnaissance de la communauté professionnelle via des présentations en conférence',
    'cases.pushkin.highlightsTitle': 'Points clés',
    'cases.pushkin.highlight1': 'Opérations de contenu à grande échelle (actifs multi-formats, distribution multi-canaux)',
    'cases.pushkin.highlight2': 'Coordination à grande échelle avec des dizaines de partenaires régionaux',
    'cases.pushkin.highlight3': 'Capacité démontrée à gérer des projets hybrides (en ligne + hors ligne)',
    'cases.pushkin.highlight4': 'Promotion du patrimoine culturel par des méthodes d\'engagement innovantes',

    // PDF Export
    'pdf.button': 'Télécharger le CV DOCX',
    'pdf.description': 'Télécharger le CV complet au format DOCX',
    'pdf.generating': 'Génération...',
    'pdf.error': 'Une erreur s\'est produite lors de la création du DOCX. Veuillez réessayer.',
    
    // Case Studies buttons
    'cases.showDetails': 'Voir les détails',
    'cases.hideDetails': 'Masquer les détails',
  } as const
} as const;

type TranslationKey = keyof typeof translations['en'];

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  function getInitialLanguage(): Language {
    if (typeof window !== 'undefined') {
      const params = new URLSearchParams(window.location.search);
      const lang = params.get('lang');
      if (lang === 'ru' || lang === 'en' || lang === 'fr') {
        return lang;
      }
    }
    return 'ru';
  }

  const [language, setLanguage] = useState<Language>(getInitialLanguage());

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'ru' : 'en');
  };

  const t = (key: TranslationKey): string => {
    return (translations as any)[language][key] || (translations as any)['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, currentLanguage: language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export default LanguageProvider;

